import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import api from "../utils/api";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import toast from "react-hot-toast";
import jsPDF from "jspdf";

const FIRDetailPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [fir, setFIR] = useState(null);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [firDraft, setFirDraft] = useState("");
  const [saving, setSaving] = useState(false);
  const [newStatus, setNewStatus] = useState("");
  const [statusNote, setStatusNote] = useState("");
  const [updatingStatus, setUpdatingStatus] = useState(false);

  useEffect(() => {
    api.get(`/fir/${id}`)
      .then((res) => {
        setFIR(res.data);
        setFirDraft(res.data.firDraft);
        setLoading(false);
      })
      .catch(() => {
        toast.error("FIR not found");
        navigate("/fir/history");
      });
  }, [id]);

  const handleUpdateStatus = async () => {
    if (!newStatus) return;
    setUpdatingStatus(true);
    try {
      const { data } = await api.post(`/fir/${id}/status`, {
        status: newStatus,
        note: statusNote,
      });
      setFIR(data);
      setNewStatus("");
      setStatusNote("");
      toast.success("Status updated!");
    } catch (err) {
      toast.error("Failed to update status");
    } finally {
      setUpdatingStatus(false);
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const { data } = await api.put(`/fir/${id}`, { firDraft });
      setFIR(data);
      setEditing(false);
      toast.success("FIR updated successfully!");
    } catch (err) {
      toast.error("Failed to update FIR");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center"
        style={{ backgroundColor: "#0f172a" }}>
        <p className="text-slate-400">Loading FIR...</p>
      </div>
    );
  }

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFillColor(30, 41, 59);
    doc.rect(0, 0, pageWidth, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("FIRST INFORMATION REPORT", pageWidth / 2, 18, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by FIR Assistant", pageWidth / 2, 28, { align: "center" });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 35, { align: "center" });

    y = 55;

    // Crime Type Badge
    doc.setFillColor(37, 99, 235);
    doc.roundedRect(margin, y, 80, 10, 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text(`Crime Type: ${fir.crimeType || "N/A"}`, margin + 5, y + 7);

    // Status Badge
    doc.setFillColor(22, 163, 74);
    doc.roundedRect(pageWidth - margin - 50, y, 50, 10, 2, 2, "F");
    doc.text(`Status: ${fir.status}`, pageWidth - margin - 45, y + 7);

    y += 20;

    // Section helper
    const addSection = (title, content) => {
      if (y > 250) { doc.addPage(); y = 20; }

      doc.setFillColor(241, 245, 249);
      doc.rect(margin, y, pageWidth - margin * 2, 8, "F");
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(title, margin + 3, y + 6);
      y += 12;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105);

      const lines = doc.splitTextToSize(content, pageWidth - margin * 2 - 5);
      lines.forEach((line) => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(line, margin + 3, y);
        y += 6;
      });
      y += 5;
    };

    // Complainant Details
    addSection("COMPLAINANT DETAILS", [
      `Name: ${fir.complainantName}`,
      `Phone: ${fir.complainantPhone}`,
      `Address: ${fir.complainantAddress}`,
    ].join("\n"));

    // Incident Details
    addSection("INCIDENT DETAILS", [
      `Date: ${fir.incidentDate}`,
      `Time: ${fir.incidentTime}`,
      `Location: ${fir.incidentLocation}`,
      `Description: ${fir.incidentDescription}`,
    ].join("\n"));

    // IPC Sections
    if (fir.ipcSections?.length > 0) {
      addSection("APPLICABLE IPC SECTIONS", fir.ipcSections.join(", "));
    }

    // Evidence Checklist
    if (fir.evidenceChecklist?.length > 0) {
      addSection("EVIDENCE CHECKLIST", fir.evidenceChecklist.map((e, i) => `${i + 1}. ${e}`).join("\n"));
    }

    // FIR Draft
    addSection("FIR DRAFT", fir.firDraft || "");

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `FIR Assistant — Page ${i} of ${pageCount} — Generated on ${new Date().toLocaleString()}`,
        pageWidth / 2, 290, { align: "center" }
      );
    }

    doc.save(`FIR_${fir.crimeType || "Draft"}_${new Date().toLocaleDateString()}.pdf`);
    toast.success("PDF downloaded successfully!");
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#0f172a" }}>
      <Navbar />
      <div className="flex">
        <Sidebar />
        <div className="flex-1 p-6 max-w-4xl">

          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div>
              <button
                onClick={() => navigate("/fir/history")}
                className="text-slate-400 hover:text-white text-sm mb-2 flex items-center gap-1 transition"
              >
                ← Back to My FIRs
              </button>
              <h1 className="text-2xl font-bold text-white">
                {fir.crimeType || "FIR Detail"}
              </h1>
              <p className="text-slate-400 text-sm mt-1">
                📍 {fir.incidentLocation} • 📅 {new Date(fir.createdAt).toLocaleDateString()}
              </p>
            </div>
            <button
              onClick={handleDownloadPDF}
              className="bg-green-600 hover:bg-green-700 text-white text-sm px-4 py-2 rounded-xl transition flex items-center gap-2"
            >
              📄 Download PDF
            </button>
            <span className={`text-sm px-4 py-2 rounded-full font-medium ${fir.status === "Draft" ? "bg-yellow-600 text-white" :
              fir.status === "Filed" ? "bg-green-600 text-white" :
                fir.status === "Under Investigation" ? "bg-blue-600 text-white" :
                  "bg-purple-600 text-white"
              }`}>
              {fir.status}
            </span>
          </div>

          {/* Complainant Details */}
          <div className="rounded-2xl p-6 mb-4" style={{ backgroundColor: "#1e293b" }}>
            <h2 className="text-white font-semibold mb-4">👤 Complainant Details</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {[
                { label: "Name", value: fir.complainantName },
                { label: "Phone", value: fir.complainantPhone },
                { label: "Address", value: fir.complainantAddress },
              ].map((item) => (
                <div key={item.label}>
                  <p className="text-slate-500 text-xs uppercase mb-1">{item.label}</p>
                  <p className="text-white text-sm">{item.value}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Incident Details */}
          <div className="rounded-2xl p-6 mb-4" style={{ backgroundColor: "#1e293b" }}>
            <h2 className="text-white font-semibold mb-4">📍 Incident Details</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
              {[
                { label: "Date", value: fir.incidentDate },
                { label: "Time", value: fir.incidentTime },
                { label: "Location", value: fir.incidentLocation },
              ].map((item) => (
                <div key={item.label}>
                  <p className="text-slate-500 text-xs uppercase mb-1">{item.label}</p>
                  <p className="text-white text-sm">{item.value}</p>
                </div>
              ))}
            </div>
            <div>
              <p className="text-slate-500 text-xs uppercase mb-1">Description</p>
              <p className="text-slate-300 text-sm leading-relaxed">{fir.incidentDescription}</p>
            </div>
          </div>

          {/* IPC Sections */}
          {fir.ipcSections?.length > 0 && (
            <div className="rounded-2xl p-6 mb-4" style={{ backgroundColor: "#1e293b" }}>
              <h2 className="text-white font-semibold mb-4">📚 IPC Sections</h2>
              <div className="flex flex-wrap gap-2">
                {fir.ipcSections.map((section, i) => (
                  <span key={i} className="bg-blue-600 text-white text-sm px-3 py-1 rounded-full">
                    {section}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Evidence Checklist */}
          {fir.evidenceChecklist?.length > 0 && (
            <div className="rounded-2xl p-6 mb-4" style={{ backgroundColor: "#1e293b" }}>
              <h2 className="text-white font-semibold mb-4">✅ Evidence Checklist</h2>
              <div className="flex flex-col gap-2">
                {fir.evidenceChecklist.map((item, i) => (
                  <div key={i} className="flex items-center gap-3 p-3 rounded-xl"
                    style={{ backgroundColor: "#0f172a" }}>
                    <span className="text-green-400">☐</span>
                    <span className="text-slate-300 text-sm">{item}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* FIR Draft */}
          <div className="rounded-2xl p-6 mb-4" style={{ backgroundColor: "#1e293b" }}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-white font-semibold">📄 FIR Draft</h2>
              <button
                onClick={() => setEditing(!editing)}
                className="text-blue-400 hover:text-blue-300 text-sm transition"
              >
                {editing ? "Cancel" : "✏️ Edit"}
              </button>
            </div>
            {editing ? (
              <div>
                <textarea
                  value={firDraft}
                  onChange={(e) => setFirDraft(e.target.value)}
                  rows={12}
                  className="w-full px-4 py-3 rounded-xl text-slate-300 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none text-sm leading-relaxed"
                  style={{ backgroundColor: "#0f172a" }}
                />
                <button
                  onClick={handleSave}
                  disabled={saving}
                  className="mt-3 bg-green-600 hover:bg-green-700 disabled:opacity-50 text-white px-6 py-2 rounded-xl text-sm transition"
                >
                  {saving ? "Saving..." : "💾 Save Changes"}
                </button>
              </div>
            ) : (
              <p className="text-slate-300 text-sm leading-relaxed whitespace-pre-wrap">
                {fir.firDraft}
              </p>
            )}
          </div>
          {/* Status Tracker */}
          <div className="rounded-2xl p-6 mb-4" style={{ backgroundColor: "#1e293b" }}>
            <h2 className="text-white font-semibold mb-4">📊 Case Timeline</h2>

            {/* Timeline */}
            <div className="flex flex-col gap-3 mb-6">
              {fir.statusHistory?.map((item, i) => (
                <div key={i} className="flex items-start gap-3">
                  <div className="flex flex-col items-center">
                    <div className="w-3 h-3 bg-blue-500 rounded-full mt-1" />
                    {i < fir.statusHistory.length - 1 && (
                      <div className="w-0.5 h-8 bg-slate-600 mt-1" />
                    )}
                  </div>
                  <div className="flex-1 pb-4">
                    <div className="flex items-center gap-2">
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${item.status === "Draft" ? "bg-yellow-600 text-white" :
                          item.status === "Filed" ? "bg-green-600 text-white" :
                            item.status === "Under Investigation" ? "bg-blue-600 text-white" :
                              "bg-purple-600 text-white"
                        }`}>
                        {item.status}
                      </span>
                      <span className="text-slate-500 text-xs">
                        {new Date(item.updatedAt).toLocaleDateString()}
                      </span>
                    </div>
                    {item.note && (
                      <p className="text-slate-400 text-sm mt-1">{item.note}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {/* Update Status */}
            <div className="border-t pt-4" style={{ borderColor: "#334155" }}>
              <p className="text-white text-sm font-medium mb-3">Update Status</p>
              <div className="flex flex-col gap-3">
                <select
                  value={newStatus}
                  onChange={(e) => setNewStatus(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                  style={{ backgroundColor: "#0f172a" }}
                >
                  <option value="">Select new status</option>
                  <option value="Draft">Draft</option>
                  <option value="Filed">Filed</option>
                  <option value="Under Investigation">Under Investigation</option>
                  <option value="Resolved">Resolved</option>
                </select>
                <input
                  type="text"
                  placeholder="Add a note (optional)"
                  value={statusNote}
                  onChange={(e) => setStatusNote(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl text-white placeholder-slate-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  style={{ backgroundColor: "#0f172a" }}
                />
                <button
                  onClick={handleUpdateStatus}
                  disabled={!newStatus || updatingStatus}
                  className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white py-3 rounded-xl transition font-medium"
                >
                  {updatingStatus ? "Updating..." : "Update Status"}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FIRDetailPage;